kind: Namespace
apiVersion: v1
metadata:
  labels:
  name: ahaz-namespace
---
kind: Deployment
apiVersion: v1
metadata:
  name: ahaz-deployment
  namespace: ahaz-namespace
spec:
  selector:
    matchLabels:
      app: ahaz-application
  replicas: 1
  template:
    metadata:
      labels:
        app: ahaz-application
    spec:
      containers:
      - name: ahaz-container
        image: cddirector/sampleapp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          
          
