kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-deployment
  namespace: demo-namespace
spec:
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: demo-application
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: demo-container
        image: cddirector/sampleapp:1
        imagePullPolicy: Always
        ports:
        - name: api
          containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: demo-service
  namespace: demo-namespace
spec:
  ports:
  - name: api
    protocol: TCP
    port: 8080
selector:
  app: demo-application
