kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: demo-deployment
spec:
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: demo-application
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-application
    spec:
      containers:
      - name: ahaz-container
        image: cddirector/sampleapp:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
