kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ahaz-deployment
  namespace: ahaz-namespace
spec:
  progressDeadlineSeconds: 10
  selector:
    matchLabels:
      app: ahaz-application
  replicas: 1
  template:
    metadata:
      labels:
        app: ahaz-application
    spec:
      containers:
      - name: ahaz-container
        image: cddirector/sampleapp:7
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
